Increased password requirements
rajitbanerjee/vax-warden pull request #70
Opened 2022-05-07 16:50 UTC by ConorHK

# Notes
* Closes #66 
## New requirements
*  8 - 64 characters
* Special character
* Uppercase character
* Lowercase character
* Number
![password_fail](https://user-images.githubusercontent.com/43848548/167263986-c90e88d2-4c36-455f-b3be-1b0b7fba7ae8.png)
![password_success](https://user-images.githubusercontent.com/43848548/167263988-97e1afa1-4700-4548-ac51-ca4da8108901.png)

2022-05-07 19:39 UTC, rajitbanerjee requested changes
Frontend nicely handled with minimal code!

2022-05-07 19:39 UTC, rajitbanerjee commented on backend/src/main/java/com/vax/warden/validation/PasswordConstraintValidator.java
> +        return false;
:nit: verbosity
```suggestion
        return result.isValid();
```

2022-05-07 19:39 UTC, rajitbanerjee commented on backend/src/main/java/com/vax/warden/model/User.java
> +    @ValidPassword(message = "Password: Invalid password")
:nit:
```suggestion
    @ValidPassword(message = "Password: Password is not strong enough!")
```

2022-05-07 19:39 UTC, rajitbanerjee commented on frontend/src/pages/Registration.tsx
>              <FormControl isRequired marginTop={6}>
Need to show invalid password message from backend on Submit attempt
```suggestion
            <FormControl isRequired marginTop={6} isInvalid={formatUserDetailsKey.password in errorMap}>
```

2022-05-07 19:39 UTC, rajitbanerjee commented on frontend/src/pages/Registration.tsx
> +              <PasswordChecklist
```suggestion
              </InputGroup>
              {getUserDetailsErrorMessage(errorMap, "password")}
              <PasswordChecklist
```
TODO: spacing between error message and password constraints list

2022-05-09 11:20 UTC, ConorHK commented on .gitignore
> +
Merged into one in source

2022-05-09 13:38 UTC, merged